

export const workFlows = {
  "home-page-workflow": [
    {
      elementSelector: "#title",
      header:"Title card",
      content: "This is the title on the Home page",
      elementType: "normal",
      hasBackButton: false,
      backButtonLabel: "Back",
      hasNextButton: true,
      nextButtonLabel: "Next",
      previousPage: null,
      previousElement:null,
      nextPage: null,
      nextElement: "#author",
    },
    {
    elementSelector: "#author",
    header:"author name",
    content: "This is the name of the author on the Home page",
    elementType: "normal",
    hasBackButton: true,
    backButtonLabel: "Back",
    hasNextButton: true,
    nextButtonLabel: "Next",
    previousPage: null,
    previousElement:null,
    nextPage: null,
    nextElement: "#slogan",
  },
  {
    elementSelector: "#slogan",
    header:"slogan",
    content: "This is the slogan section on the Home page",
    elementType: "normal",
    hasBackButton: true,
    backButtonLabel: "Back",
    hasNextButton: true,
    nextButtonLabel: "Next",
    previousPage: null,
    previousElement:"author",
    nextPage: null,
    nextElement: "#welcome",
  },
  {
    elementSelector: "#welcome",
    header:"welcoming you",
    content: "This is the welcome section on the Home page",
    elementType: "normal",
    hasBackButton: true,
    backButtonLabel: "Back",
    hasNextButton: true,
    nextButtonLabel: "Next",
    previousPage: null,
    previousElement:"slogan",
    nextPage: null,
    nextElement: "#about1",
  },
  {
    elementSelector: "#about1",
    header:"Link to about",
    content: "This is the link to join section on the about page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextPage: "/about",
    nextElement: "#highlights",
    previousElement:null,
    previousPage: null,
  },
],
"about-page-workflow": [
  {
    elementSelector: "#highlights",
    header:"highlighted section",
    content: "This is the highlight section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#certificates",
    previousElement: "#company-profile",
    previousPage: "/home",
    nextPage: null,
  
  },
  {
    elementSelector: "#certificates",
    header:"certificates",
    content: "This is the certificates section on the Home page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    previousElement: "#highlights",
    nextElement: "#slogan",
    nextPage: null,
    previousPage: null,
  },
  {
    elementSelector: "#why",
    header:"why is this",
    content: "This is the why section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#home",
    nextPage: "/home",
    previousElement:"certificates",
  },
],

"home-page-workflow2":  [
  {
    elementSelector: "#home",
    header:"Home page ",
    content: "This is the home tab on the Home page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextPage: "/home",
    nextElement: "#company-profile",
    previousPage: "/about",
    previousElement: "#why",
  },
  {
    elementSelector: "#company-profile",
    header:"profile of the company",
    content: "This is the company profile section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/home",
    previousElement: "#about1",
    nextElement: "#process-page",
  },
],
"process-page-workflow": [
  {
    elementSelector: "#process",
    header:"process page link",
    content: "This is the process section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/home",
    previousElement: "#company-profile",
    nextPage: "/process",
    nextElement: "#process-page",
  },
  {
    elementSelector: "#process-page",
    header:"process page ",
    content: "This is the process page section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    nextElement: "#processed",
  },
  {
    elementSelector: "#processed",
    header:"second process",
    content: "This is the processed section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    nextElement: "#products",
  },
],
"product-page-workflow":[
  {
    elementSelector: "#products",
    header:"products page link",
    content: "This is the products section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/process",
    previousElement: "#processed",
    nextElement: "#product-id",
    nextPage: "/products",
  },
  {
    elementSelector: "#product-id",
    header:"first product",
    content: "This is the  product details section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#contact",
    buttonAction: "moveToNextStep",

  },
],
"contact-page-workflow":  [
  {
    elementSelector: "#contact",
    header:"contact page",
    content: "This is the  contact section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/products",
    previousElement: "#product-id",
    nextPage: "/contact",
    nextElement: "#enquiry",
  },
  {
    elementSelector: "#enquiry",
    header:"enquire here",
    content: "This is the enquiry section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    nextElement: "#mail",
  },
  {
    elementSelector: "#mail",
    header:"mail id here",
    content: "This is the mail section on the About page",
    elementType: "button",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    nextElement: "#submit",
  },
  {
    elementSelector: "#submit",
    header:"click to submit",
    content: "This is the about head section on the About page",
    elementType: "button",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    nextPage: "/home"
  },
]
}








