export const tourSteps = [
  {
    elementSelector: "#author",
    content: "This is the name of the author on the Home page",
    elementType: "normal",
    hasBackButton: false,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#slogan",
    previousElement:null,
    nextPage: null,
    previousPage: null,
  },
  {
    elementSelector: "#slogan",
    content: "This is the slogan section on the Home page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#welcome",
    previousElement:"author",
    nextPage: null,
    previousPage: null,
  },
  {
    elementSelector: "#welcome",
    content: "This is the welcome section on the Home page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#about1",
    previousElement:"slogan",
    nextPage: null,
    previousPage: null,
  },
  {
    elementSelector: "#about1",
    content: "This is the link to join section on the about page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextPage: "/about",
    nextElement: "#highlights",
    previousElement:null,
    previousPage: null,
  },
  {
    elementSelector: "#highlights",
    content: "This is the highlight section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#certificates",
    previousElement: "#company-profile",
    previousPage: "/home",
    nextPage: null,
  
  },
  {
    elementSelector: "#certificates",
    content: "This is the certificates section on the Home page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    previousElement: "#highlights",
    nextElement: "#slogan",
    nextPage: null,
    previousPage: null,
  },
  {
    elementSelector: "#why",
    content: "This is the why section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextElement: "#home",
    nextPage: "/home",
    previousElement:"certificates",
  },
  {
    elementSelector: "#home",
    content: "This is the home tab on the Home page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    nextPage: "/home",
    previousPage: "/about",
    previousElement: "#why",
  },
  {
    elementSelector: "#company-profile",
    content: "This is the company profile section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/home",
    previousElement: "#about1",
    nextElement: "#certificates",
  },
  {
    elementSelector: "#process",
    content: "This is the process section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/home",
    previousElement: "#company-profile",
    nextPage: "/process",
  },
  {
    elementSelector: "#process-page",
    content: "This is the process page section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
  },
  {
    elementSelector: "#processed",
    content: "This is the processed section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
  },
  {
    elementSelector: "#products",
    content: "This is the products section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/process",
    previousElement: "#processed",
    nextPage: "/products",
  },
  {
    elementSelector: "#product-id",
    content: "This is the  product details section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
  },
  {
    elementSelector: "#contact",
    content: "This is the  contact section on the About page",
    elementType: "link",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
    previousPage: "/products",
    previousElement: "#product-id",
    nextPage: "/contact",
  },
  {
    elementSelector: "#enquiry",
    content: "This is the enquiry section on the About page",
    elementType: "normal",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
  },
  {
    elementSelector: "#mail",
    content: "This is the mail section on the About page",
    elementType: "button",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
  },
  {
    elementSelector: "#submit",
    content: "This is the about head section on the About page",
    elementType: "button",
    hasBackButton: true,
    hasNextButton: true,
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    buttonAction: "moveToNextStep",
  },
];
