export const tourSteps = [
    {
        "elementSelector": "#author",
        "content": "This is the name of the author on the Home page",
        "elementType": "normal",
        "hasBackButton": false,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "nextElement":"#slogan",
        "completed": false,
        "step": 0
      },
      {
        "elementSelector": "#slogan",
        "content": "This is the slogan section on the Home page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "nextElement":"#welcome",
        "completed": false,
        "step": 1
      },
      {
        "elementSelector": "#welcome",
        "content": "This is the welcome section on the Home page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "nextElement":"#about1",
        "completed": false,
        "step": 2
      },
      {
        "elementSelector": "#about1",
        "content": "This is the welcome section on the Home page",
        "elementType": "link",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "visited": false,
        "completed": false,
        "nextPage": "/about",
        "nextElement":"#highlights",
        "step": 3
      },
      {
        "elementSelector": "#highlights",
        "content": "This is the about head section on the About page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "previousPage":"/home",
        "completed": false,
        "previousElement":"#company-profile",
        "nextElement":"#certificates",
        "step": 4
      },
      {
        "elementSelector": "#certificates",
        "content": "This is the welcome section on the Home page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "nextElement":"#why",
        "completed": false,
        "step": 5
      },
      {
        "elementSelector": "#why",
        "content": "This is the about head section on the About page",
        "elementType": "link",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "nextPage":"/home",
        "nextElement":"#company-profile",
        "completed": false,
        "step": 6
      },
      {
        "elementSelector": "#home",
        "content": "This is the welcome section on the Home page",
        "elementType": "link",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "nextPage": "/home",
        "completed": false,
        "step": 7
      },
      {
        "elementSelector": "#company-profile",
        "content": "This is the about head section on the About page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "completed": false,
        "step": 8
      },
      {
        "elementSelector": "#process",
        "content": "This is the about head section on the About page",
        "elementType": "link",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "nextPage": "/process",
        "completed": false,
        "step": 9
      },
      {
        "elementSelector": "#process-page",
        "content": "This is the about head section on the About page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "completed": false,
        "step": 10
      }
    ,
      {
        "elementSelector": "#processed",
        "content": "This is the about head section on the About page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "completed": false,
        "step": 11
      },
      {
        "elementSelector": "#products",
        "content": "This is the about head section on the About page",
        "elementType": "link",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction":"moveToNextStep",
        "nextPage": "/products",
        "completed": false,
        "step": 12
      }, 
        {
        "elementSelector": "#product-id",
        "content": "This is the about head section on the About page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction":"moveToNextStep",
        "completed": false,
        "step": 13
      },
      {
        "elementSelector": "#contact",
        "content": "This is the about head section on the About page",
        "elementType": "link",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "nextPage": "/contact",
        "completed": false,
        "step": 14
      },
      {
        "elementSelector": "#enquiry",
        "content": "This is the about head section on the About page",
        "elementType": "normal",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "completed": false,
        "step": 15
      }, 
      {
        "elementSelector": "#mail",
        "content": "This is the about head section on the About page",
        "elementType": "button",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "completed": false,
        "step": 16
      }, {
        "elementSelector": "#submit",
        "content": "This is the about head section on the About page",
        "elementType": "button",
        "hasBackButton": true,
        "hasNextButton": true,
        "backButtonLabel": "Back",
        "nextButtonLabel": "Next",
        "buttonAction": "moveToNextStep",
        "completed": false,
        "step": 16
      }
]